import { BiQuestionMark } from "react-icons/bi";

const ICON_SIZE = "30";
export const CareerLists = [
  {
    position: "Fullstack Developer",
    company: "Coming soon",
    logo: "https://res.cloudinary.com/dxgsqxdi3/image/upload/f_auto,q_auto/ukhe5phqaai5gq6nmtie",
    location: "Jakarta, ID",
    location_type: "Remote",
    type: "Fulltime",
    start_date: "2022-07",
    end_date: "2023-07",
    industry: "wellness",
    link: "https://ryznox.my.id",
  },
  {
    position: "Fullstack Developer",
    company: "Coming soon",
    logo: "https://res.cloudinary.com/dxgsqxdi3/image/upload/f_auto,q_auto/ukhe5phqaai5gq6nmtie",
    location: "Surakarta, ID",
    location_type: "Remote",
    type: "Fulltime",
    start_date: "2022-03",
    end_date: "2023-07",
    industry: "wellness",
    link: "https://ryznox.my.id",
  },
  {
    position: "Fullstack Developer",
    company: "Coming soon",
    logo: "https://res.cloudinary.com/dxgsqxdi3/image/upload/f_auto,q_auto/ukhe5phqaai5gq6nmtie",
    location: "Surabaya, ID",
    location_type: "Remote",
    type: "Fulltime",
    start_date: "2022-03",
    end_date: "2023-07",
    industry: "wellness",
    link: "https://ryznox.my.id",
  },
  {
    position: "Fullstack Developer",
    company: "Coming soon",
    logo: "https://res.cloudinary.com/dxgsqxdi3/image/upload/f_auto,q_auto/ukhe5phqaai5gq6nmtie",
    location: "Malang, ID",
    location_type: "Remote",
    type: "Fulltime",
    start_date: "2023-09",
    end_date: null,
    industry: "software house",
    link: "https://ryznox.my.id",
  },
];
